# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Proj/proj/RobotProjects/rhsplib/librhsp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Proj/proj/RobotProjects/rhsplib/librhsp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Proj/proj/RobotProjects/rhsplib/librhsp/CMakeFiles /Volumes/Proj/proj/RobotProjects/rhsplib/librhsp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Proj/proj/RobotProjects/rhsplib/librhsp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rhsp

# Build rule for target.
rhsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rhsp
.PHONY : rhsp

# fast build rule for target.
rhsp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/build
.PHONY : rhsp/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/arch/mac/serial.o: src/arch/mac/serial.c.o
.PHONY : src/arch/mac/serial.o

# target to build an object file
src/arch/mac/serial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/serial.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/serial.c.o
.PHONY : src/arch/mac/serial.c.o

src/arch/mac/serial.i: src/arch/mac/serial.c.i
.PHONY : src/arch/mac/serial.i

# target to preprocess a source file
src/arch/mac/serial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/serial.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/serial.c.i
.PHONY : src/arch/mac/serial.c.i

src/arch/mac/serial.s: src/arch/mac/serial.c.s
.PHONY : src/arch/mac/serial.s

# target to generate assembly for a file
src/arch/mac/serial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/serial.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/serial.c.s
.PHONY : src/arch/mac/serial.c.s

src/arch/mac/time.o: src/arch/mac/time.c.o
.PHONY : src/arch/mac/time.o

# target to build an object file
src/arch/mac/time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/time.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/time.c.o
.PHONY : src/arch/mac/time.c.o

src/arch/mac/time.i: src/arch/mac/time.c.i
.PHONY : src/arch/mac/time.i

# target to preprocess a source file
src/arch/mac/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/time.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/time.c.i
.PHONY : src/arch/mac/time.c.i

src/arch/mac/time.s: src/arch/mac/time.c.s
.PHONY : src/arch/mac/time.s

# target to generate assembly for a file
src/arch/mac/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/arch/mac/time.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/arch/mac/time.c.s
.PHONY : src/arch/mac/time.c.s

src/command.o: src/command.c.o
.PHONY : src/command.o

# target to build an object file
src/command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/command.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/command.c.o
.PHONY : src/command.c.o

src/command.i: src/command.c.i
.PHONY : src/command.i

# target to preprocess a source file
src/command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/command.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/command.c.i
.PHONY : src/command.c.i

src/command.s: src/command.c.s
.PHONY : src/command.s

# target to generate assembly for a file
src/command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/command.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/command.c.s
.PHONY : src/command.c.s

src/deviceControl.o: src/deviceControl.c.o
.PHONY : src/deviceControl.o

# target to build an object file
src/deviceControl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/deviceControl.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/deviceControl.c.o
.PHONY : src/deviceControl.c.o

src/deviceControl.i: src/deviceControl.c.i
.PHONY : src/deviceControl.i

# target to preprocess a source file
src/deviceControl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/deviceControl.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/deviceControl.c.i
.PHONY : src/deviceControl.c.i

src/deviceControl.s: src/deviceControl.c.s
.PHONY : src/deviceControl.s

# target to generate assembly for a file
src/deviceControl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/deviceControl.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/deviceControl.c.s
.PHONY : src/deviceControl.c.s

src/dio.o: src/dio.c.o
.PHONY : src/dio.o

# target to build an object file
src/dio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/dio.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/dio.c.o
.PHONY : src/dio.c.o

src/dio.i: src/dio.c.i
.PHONY : src/dio.i

# target to preprocess a source file
src/dio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/dio.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/dio.c.i
.PHONY : src/dio.c.i

src/dio.s: src/dio.c.s
.PHONY : src/dio.s

# target to generate assembly for a file
src/dio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/dio.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/dio.c.s
.PHONY : src/dio.c.s

src/i2c.o: src/i2c.c.o
.PHONY : src/i2c.o

# target to build an object file
src/i2c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/i2c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/i2c.c.o
.PHONY : src/i2c.c.o

src/i2c.i: src/i2c.c.i
.PHONY : src/i2c.i

# target to preprocess a source file
src/i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/i2c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/i2c.c.i
.PHONY : src/i2c.c.i

src/i2c.s: src/i2c.c.s
.PHONY : src/i2c.s

# target to generate assembly for a file
src/i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/i2c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/i2c.c.s
.PHONY : src/i2c.c.s

src/module.o: src/module.c.o
.PHONY : src/module.o

# target to build an object file
src/module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/module.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/module.c.o
.PHONY : src/module.c.o

src/module.i: src/module.c.i
.PHONY : src/module.i

# target to preprocess a source file
src/module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/module.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/module.c.i
.PHONY : src/module.c.i

src/module.s: src/module.c.s
.PHONY : src/module.s

# target to generate assembly for a file
src/module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/module.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/module.c.s
.PHONY : src/module.c.s

src/motor.o: src/motor.c.o
.PHONY : src/motor.o

# target to build an object file
src/motor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/motor.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/motor.c.o
.PHONY : src/motor.c.o

src/motor.i: src/motor.c.i
.PHONY : src/motor.i

# target to preprocess a source file
src/motor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/motor.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/motor.c.i
.PHONY : src/motor.c.i

src/motor.s: src/motor.c.s
.PHONY : src/motor.s

# target to generate assembly for a file
src/motor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/motor.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/motor.c.s
.PHONY : src/motor.c.s

src/packet.o: src/packet.c.o
.PHONY : src/packet.o

# target to build an object file
src/packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/packet.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/packet.c.o
.PHONY : src/packet.c.o

src/packet.i: src/packet.c.i
.PHONY : src/packet.i

# target to preprocess a source file
src/packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/packet.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/packet.c.i
.PHONY : src/packet.c.i

src/packet.s: src/packet.c.s
.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/packet.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/packet.c.s
.PHONY : src/packet.c.s

src/revhub.o: src/revhub.c.o
.PHONY : src/revhub.o

# target to build an object file
src/revhub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/revhub.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/revhub.c.o
.PHONY : src/revhub.c.o

src/revhub.i: src/revhub.c.i
.PHONY : src/revhub.i

# target to preprocess a source file
src/revhub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/revhub.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/revhub.c.i
.PHONY : src/revhub.c.i

src/revhub.s: src/revhub.c.s
.PHONY : src/revhub.s

# target to generate assembly for a file
src/revhub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/revhub.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/revhub.c.s
.PHONY : src/revhub.c.s

src/rhsp.o: src/rhsp.c.o
.PHONY : src/rhsp.o

# target to build an object file
src/rhsp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/rhsp.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/rhsp.c.o
.PHONY : src/rhsp.c.o

src/rhsp.i: src/rhsp.c.i
.PHONY : src/rhsp.i

# target to preprocess a source file
src/rhsp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/rhsp.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/rhsp.c.i
.PHONY : src/rhsp.c.i

src/rhsp.s: src/rhsp.c.s
.PHONY : src/rhsp.s

# target to generate assembly for a file
src/rhsp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/rhsp.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/rhsp.c.s
.PHONY : src/rhsp.c.s

src/servo.o: src/servo.c.o
.PHONY : src/servo.o

# target to build an object file
src/servo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/servo.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/servo.c.o
.PHONY : src/servo.c.o

src/servo.i: src/servo.c.i
.PHONY : src/servo.i

# target to preprocess a source file
src/servo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/servo.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/servo.c.i
.PHONY : src/servo.c.i

src/servo.s: src/servo.c.s
.PHONY : src/servo.s

# target to generate assembly for a file
src/servo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhsp.dir/build.make CMakeFiles/rhsp.dir/src/servo.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/servo.c.s
.PHONY : src/servo.c.s

test/src/Environment.o: test/src/Environment.cpp.o
.PHONY : test/src/Environment.o

# target to build an object file
test/src/Environment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/Environment.cpp.o
.PHONY : test/src/Environment.cpp.o

test/src/Environment.i: test/src/Environment.cpp.i
.PHONY : test/src/Environment.i

# target to preprocess a source file
test/src/Environment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/Environment.cpp.i
.PHONY : test/src/Environment.cpp.i

test/src/Environment.s: test/src/Environment.cpp.s
.PHONY : test/src/Environment.s

# target to generate assembly for a file
test/src/Environment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/Environment.cpp.s
.PHONY : test/src/Environment.cpp.s

test/src/RhspConfig.o: test/src/RhspConfig.cpp.o
.PHONY : test/src/RhspConfig.o

# target to build an object file
test/src/RhspConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/RhspConfig.cpp.o
.PHONY : test/src/RhspConfig.cpp.o

test/src/RhspConfig.i: test/src/RhspConfig.cpp.i
.PHONY : test/src/RhspConfig.i

# target to preprocess a source file
test/src/RhspConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/RhspConfig.cpp.i
.PHONY : test/src/RhspConfig.cpp.i

test/src/RhspConfig.s: test/src/RhspConfig.cpp.s
.PHONY : test/src/RhspConfig.s

# target to generate assembly for a file
test/src/RhspConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/RhspConfig.cpp.s
.PHONY : test/src/RhspConfig.cpp.s

test/src/basictest.o: test/src/basictest.cpp.o
.PHONY : test/src/basictest.o

# target to build an object file
test/src/basictest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/basictest.cpp.o
.PHONY : test/src/basictest.cpp.o

test/src/basictest.i: test/src/basictest.cpp.i
.PHONY : test/src/basictest.i

# target to preprocess a source file
test/src/basictest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/basictest.cpp.i
.PHONY : test/src/basictest.cpp.i

test/src/basictest.s: test/src/basictest.cpp.s
.PHONY : test/src/basictest.s

# target to generate assembly for a file
test/src/basictest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/basictest.cpp.s
.PHONY : test/src/basictest.cpp.s

test/src/devicecontroltest.o: test/src/devicecontroltest.cpp.o
.PHONY : test/src/devicecontroltest.o

# target to build an object file
test/src/devicecontroltest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/devicecontroltest.cpp.o
.PHONY : test/src/devicecontroltest.cpp.o

test/src/devicecontroltest.i: test/src/devicecontroltest.cpp.i
.PHONY : test/src/devicecontroltest.i

# target to preprocess a source file
test/src/devicecontroltest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/devicecontroltest.cpp.i
.PHONY : test/src/devicecontroltest.cpp.i

test/src/devicecontroltest.s: test/src/devicecontroltest.cpp.s
.PHONY : test/src/devicecontroltest.s

# target to generate assembly for a file
test/src/devicecontroltest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/devicecontroltest.cpp.s
.PHONY : test/src/devicecontroltest.cpp.s

test/src/diotest.o: test/src/diotest.cpp.o
.PHONY : test/src/diotest.o

# target to build an object file
test/src/diotest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/diotest.cpp.o
.PHONY : test/src/diotest.cpp.o

test/src/diotest.i: test/src/diotest.cpp.i
.PHONY : test/src/diotest.i

# target to preprocess a source file
test/src/diotest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/diotest.cpp.i
.PHONY : test/src/diotest.cpp.i

test/src/diotest.s: test/src/diotest.cpp.s
.PHONY : test/src/diotest.s

# target to generate assembly for a file
test/src/diotest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/diotest.cpp.s
.PHONY : test/src/diotest.cpp.s

test/src/discoverytest.o: test/src/discoverytest.cpp.o
.PHONY : test/src/discoverytest.o

# target to build an object file
test/src/discoverytest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/discoverytest.cpp.o
.PHONY : test/src/discoverytest.cpp.o

test/src/discoverytest.i: test/src/discoverytest.cpp.i
.PHONY : test/src/discoverytest.i

# target to preprocess a source file
test/src/discoverytest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/discoverytest.cpp.i
.PHONY : test/src/discoverytest.cpp.i

test/src/discoverytest.s: test/src/discoverytest.cpp.s
.PHONY : test/src/discoverytest.s

# target to generate assembly for a file
test/src/discoverytest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/discoverytest.cpp.s
.PHONY : test/src/discoverytest.cpp.s

test/src/i2ctest.o: test/src/i2ctest.cpp.o
.PHONY : test/src/i2ctest.o

# target to build an object file
test/src/i2ctest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/i2ctest.cpp.o
.PHONY : test/src/i2ctest.cpp.o

test/src/i2ctest.i: test/src/i2ctest.cpp.i
.PHONY : test/src/i2ctest.i

# target to preprocess a source file
test/src/i2ctest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/i2ctest.cpp.i
.PHONY : test/src/i2ctest.cpp.i

test/src/i2ctest.s: test/src/i2ctest.cpp.s
.PHONY : test/src/i2ctest.s

# target to generate assembly for a file
test/src/i2ctest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/i2ctest.cpp.s
.PHONY : test/src/i2ctest.cpp.s

test/src/motortest.o: test/src/motortest.cpp.o
.PHONY : test/src/motortest.o

# target to build an object file
test/src/motortest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/motortest.cpp.o
.PHONY : test/src/motortest.cpp.o

test/src/motortest.i: test/src/motortest.cpp.i
.PHONY : test/src/motortest.i

# target to preprocess a source file
test/src/motortest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/motortest.cpp.i
.PHONY : test/src/motortest.cpp.i

test/src/motortest.s: test/src/motortest.cpp.s
.PHONY : test/src/motortest.s

# target to generate assembly for a file
test/src/motortest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/motortest.cpp.s
.PHONY : test/src/motortest.cpp.s

test/src/pwmservotest.o: test/src/pwmservotest.cpp.o
.PHONY : test/src/pwmservotest.o

# target to build an object file
test/src/pwmservotest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/pwmservotest.cpp.o
.PHONY : test/src/pwmservotest.cpp.o

test/src/pwmservotest.i: test/src/pwmservotest.cpp.i
.PHONY : test/src/pwmservotest.i

# target to preprocess a source file
test/src/pwmservotest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/pwmservotest.cpp.i
.PHONY : test/src/pwmservotest.cpp.i

test/src/pwmservotest.s: test/src/pwmservotest.cpp.s
.PHONY : test/src/pwmservotest.s

# target to generate assembly for a file
test/src/pwmservotest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/pwmservotest.cpp.s
.PHONY : test/src/pwmservotest.cpp.s

test/src/utils.o: test/src/utils.cpp.o
.PHONY : test/src/utils.o

# target to build an object file
test/src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/utils.cpp.o
.PHONY : test/src/utils.cpp.o

test/src/utils.i: test/src/utils.cpp.i
.PHONY : test/src/utils.i

# target to preprocess a source file
test/src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/utils.cpp.i
.PHONY : test/src/utils.cpp.i

test/src/utils.s: test/src/utils.cpp.s
.PHONY : test/src/utils.s

# target to generate assembly for a file
test/src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/src/utils.cpp.s
.PHONY : test/src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... rhsp"
	@echo "... tests"
	@echo "... src/arch/mac/serial.o"
	@echo "... src/arch/mac/serial.i"
	@echo "... src/arch/mac/serial.s"
	@echo "... src/arch/mac/time.o"
	@echo "... src/arch/mac/time.i"
	@echo "... src/arch/mac/time.s"
	@echo "... src/command.o"
	@echo "... src/command.i"
	@echo "... src/command.s"
	@echo "... src/deviceControl.o"
	@echo "... src/deviceControl.i"
	@echo "... src/deviceControl.s"
	@echo "... src/dio.o"
	@echo "... src/dio.i"
	@echo "... src/dio.s"
	@echo "... src/i2c.o"
	@echo "... src/i2c.i"
	@echo "... src/i2c.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/motor.o"
	@echo "... src/motor.i"
	@echo "... src/motor.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/revhub.o"
	@echo "... src/revhub.i"
	@echo "... src/revhub.s"
	@echo "... src/rhsp.o"
	@echo "... src/rhsp.i"
	@echo "... src/rhsp.s"
	@echo "... src/servo.o"
	@echo "... src/servo.i"
	@echo "... src/servo.s"
	@echo "... test/src/Environment.o"
	@echo "... test/src/Environment.i"
	@echo "... test/src/Environment.s"
	@echo "... test/src/RhspConfig.o"
	@echo "... test/src/RhspConfig.i"
	@echo "... test/src/RhspConfig.s"
	@echo "... test/src/basictest.o"
	@echo "... test/src/basictest.i"
	@echo "... test/src/basictest.s"
	@echo "... test/src/devicecontroltest.o"
	@echo "... test/src/devicecontroltest.i"
	@echo "... test/src/devicecontroltest.s"
	@echo "... test/src/diotest.o"
	@echo "... test/src/diotest.i"
	@echo "... test/src/diotest.s"
	@echo "... test/src/discoverytest.o"
	@echo "... test/src/discoverytest.i"
	@echo "... test/src/discoverytest.s"
	@echo "... test/src/i2ctest.o"
	@echo "... test/src/i2ctest.i"
	@echo "... test/src/i2ctest.s"
	@echo "... test/src/motortest.o"
	@echo "... test/src/motortest.i"
	@echo "... test/src/motortest.s"
	@echo "... test/src/pwmservotest.o"
	@echo "... test/src/pwmservotest.i"
	@echo "... test/src/pwmservotest.s"
	@echo "... test/src/utils.o"
	@echo "... test/src/utils.i"
	@echo "... test/src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

